// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompositionController from "./composition_controller"
application.register("composition", CompositionController)

import GigController from "./gig_controller"
application.register("gig", GigController)

import ImageTableController from "./image_table_controller"
application.register("image-table", ImageTableController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import LocalTimeController from "./local_time_controller"
application.register("local-time", LocalTimeController)

import MapController from "./map_controller"
application.register("map", MapController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TableController from "./table_controller"
application.register("table", TableController)

import VenueController from "./venue_controller"
application.register("venue", VenueController)
